name: the gridster
favicon: null
layout_spectrum: 0.32565431855618954
typography_spectrum: 0.7982999088708311
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3182953696232289
  lightness: 0.209334785817191
  saturation: 0.9943682362791151
  rhythmicContrast: 0.8935278095304966
purpose: []
